const data = {
    products:[
        {
            _id:'1',
            name:'DPR Live - Her',
            category:'Hip-Hop',
            image:'/images/her.jpg',
            price: 14.99,
            artist:'DPR Live',
            rating: 5,
            numReviews: 1,
            description: 'Coming to you live',
        },
        {
            _id:'2',
            name:'Sik-k - H.A.L.F',
            category:'Hip-Hop',
            image:'/images/half.jpg',
            price: 17.99,
            artist:'Sik-k',
            rating: 5,
            numReviews: 1,
            description: 'Have A Little Fun',
        },
        {
            _id:'3',
            name:'Yuzion - Young Trapper',
            category:'Hip-Hop',
            image:'/images/youngtrapper.jpg',
            price: 14.99,
            artist:'Yuzion',
            rating: 5,
            numReviews: 1,
            description: 'Look at me',
        },
        {
            _id:'4',
            name:'pH-1 - HALO',
            category:'Hip-Hop',
            image:'/images/halo.jpg',
            price: 14.99,
            artist:'pH-1',
            rating: 5,
            numReviews: 1,
            description: 'Homebody',
        },
        {
            _id:'5',
            name:'Superbee - Rap Legend 2',
            category:'Hip-Hop',
            image:'/images/raplegend2.jpg',
            price: 16.99,
            artist:'Superbee',
            rating: 5,
            numReviews: 1,
            description: 'self-made orange',
        },
        {
            _id:'6',
            name:'Sik-k - FL1P',
            category:'Hip-Hop',
            image:'/images/fl1p.jpg',
            price: 17.99,
            artist:'Sik-K',
            rating: 5,
            numReviews: 1,
            description: 'Runnin',
        },
    ],
};

export default data;